language: csharp
mono: none
dotnet: 6.0.100

os:
  - linux
  - osx 

script:
  - dotnet restore
  - dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f net6.0
  - dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f net6.0
  - dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f net6.0