language: csharp
dotnet: 3.1
mono: none

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then ulimit -n 2048; fi
  
before_script:
  - dotnet restore

script:
  - dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f netcoreapp3.0
  - dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f netcoreapp3.1
  - dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f netcoreapp3.0
  - dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f netcoreapp3.1
  - dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f netcoreapp3.0
  - dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f netcoreapp3.1

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
    - os: osx
      dotnet: 3.1.100
      osx_image: xcode11.2