environment:
  build_version: 5.1.0

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2022

skip_commits:
  files:
    - .github/
    - '**/*.md'

install:
- dotnet tool install -g InheritDocTool

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(build_version)
  package_version: $(build_version)
  assembly_version: $(build_version)
  file_version: $(build_version)
  informational_version: $(build_version)

build_script:
- dotnet restore stashbox.extensions.dependencyinjection.sln
- dotnet build -c %configuration% /p:ContinuousIntegrationBuild=true stashbox.extensions.dependencyinjection.sln
  
after_build:
- inheritdoc -o
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\..\artifacts src\stashbox.aspnetcore.hosting\stashbox.aspnetcore.hosting.csproj
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\..\artifacts src\stashbox.extensions.dependencyinjection\stashbox.extensions.dependencyinjection.csproj
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\..\artifacts src\stashbox.extensions.hosting\stashbox.extensions.hosting.csproj
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\..\artifacts src\stashbox.aspnetcore.multitenant\stashbox.aspnetcore.multitenant.csproj
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\..\artifacts src\stashbox.aspnetcore.testing\stashbox.aspnetcore.testing.csproj

test_script:
- dotnet test test\stashbox.extensions.dependencyinjection.specificationtests\stashbox.extensions.dependencyinjection.specificationtests.csproj -f netcoreapp3.1 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.extensions.dependencyinjection.specificationtests\stashbox.extensions.dependencyinjection.specificationtests.csproj -f net6.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.extensions.dependencyinjection.tests\stashbox.extensions.dependencyinjection.tests.csproj -f netcoreapp3.1 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.extensions.dependencyinjection.tests\stashbox.extensions.dependencyinjection.tests.csproj -f net6.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.multitenant.tests\stashbox.aspnetcore.multitenant.tests.csproj -f netcoreapp3.1 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.multitenant.tests\stashbox.aspnetcore.multitenant.tests.csproj -f net6.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.multitenant.tests\stashbox.aspnetcore.multitenant.tests.csproj -f net7.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.testing.tests\stashbox.aspnetcore.testing.tests.csproj -f net6.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.testing.tests\stashbox.aspnetcore.testing.tests.csproj -f net7.0 -c %CONFIGURATION% --no-build
  
artifacts:
  - path: artifacts\Stashbox.*.nupkg
    name: NuGet Packages
  - path: artifacts\Stashbox.*.snupkg
    name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true