environment:
  build_version: 2.11.1

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2019

install:
- dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 src\stashbox.aspnetcore.hosting\stashbox.aspnetcore.hosting.csproj $($env:build_version)
- ps: . .\patch-version.ps1 src\stashbox.extensions.dependencyinjection\stashbox.extensions.dependencyinjection.csproj $($env:build_version)
- ps: . .\patch-version.ps1 src\stashbox.extensions.hosting\stashbox.extensions.hosting.csproj $($env:build_version)
- ps: . .\patch-version.ps1 src\stashbox.aspnetcore.multitenant\stashbox.aspnetcore.multitenant.csproj $($env:build_version)

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% stashbox.extensions.dependencyinjection.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% stashbox.extensions.dependencyinjection.sln
  
after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.aspnetcore.hosting\stashbox.aspnetcore.hosting.csproj
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.extensions.dependencyinjection\stashbox.extensions.dependencyinjection.csproj
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.extensions.hosting\stashbox.extensions.hosting.csproj
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.aspnetcore.multitenant\stashbox.aspnetcore.multitenant.csproj

test_script:
- dotnet test test\stashbox.extensions.dependencyinjection.specificationtests\stashbox.extensions.dependencyinjection.specificationtests.csproj -f netcoreapp3.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.extensions.dependencyinjection.tests\stashbox.extensions.dependencyinjection.tests.csproj -f netcoreapp3.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.extensions.dependencyinjection.tests\stashbox.extensions.dependencyinjection.tests.csproj -f netcoreapp3.1 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.multitenant.tests\stashbox.aspnetcore.multitenant.tests.csproj -f netcoreapp3.0 -c %CONFIGURATION% --no-build
- dotnet test test\stashbox.aspnetcore.multitenant.tests\stashbox.aspnetcore.multitenant.tests.csproj -f netcoreapp3.1 -c %CONFIGURATION% --no-build
  
artifacts:
  - path: artifacts\Stashbox.*.nupkg
    name: NuGet Packages
  - path: artifacts\Stashbox.*.snupkg
    name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true