name: Build on Linux and macOS
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - 'appveyor*'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-test:
    name: Build & test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-13, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: dotnet restore
      - name: Test
        run: |
          dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f netcoreapp3.1 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f net5.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f net6.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f net7.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f net8.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f netcoreapp3.1 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f net5.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f net6.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f net7.0 --no-restore
          dotnet test test/stashbox.extensions.dependencyinjection.tests/stashbox.extensions.dependencyinjection.tests.csproj -c Release -f net8.0 --no-restore
          dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f netcoreapp3.1 --no-restore
          dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f net5.0 --no-restore
          dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f net6.0 --no-restore
          dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f net7.0 --no-restore
          dotnet test test/stashbox.aspnetcore.multitenant.tests/stashbox.aspnetcore.multitenant.tests.csproj -c Release -f net8.0 --no-restore
          dotnet test test/stashbox.aspnetcore.testing.tests/stashbox.aspnetcore.testing.tests.csproj -c Release -f net6.0 --no-restore
          dotnet test test/stashbox.aspnetcore.testing.tests/stashbox.aspnetcore.testing.tests.csproj -c Release -f net7.0 --no-restore
          dotnet test test/stashbox.aspnetcore.testing.tests/stashbox.aspnetcore.testing.tests.csproj -c Release -f net8.0 --no-restore